export const SET_COMPANY_LOADER = "SET_COMPANY_LOADER";
export const SET_COMPANY_FAIL = "SET_COMPANY_FAIL";
export const COMPANY_LIST_SUCCESS = "COMPANY_LIST_SUCCESS";
export const COMPANY_ADD_SUCCESS = "COMPANY_ADD_SUCCESS";
export const SET_COMPANY_RESET = "SET_COMPANY_RESET";
export const COMPANY_SEARCH = "COMPANY_SEARCH";
